### ISSUE TITLE
InterestOverTime working only for 'now 1-H'

### ISSUE THREAD

**Issue by tlatorre** [x-fran/g-trends#11] opened 2018-12-29 12:21 UTC
Thanks for this API ;)

I was getting an empty response from changing the example at index.php
~~~~
 #49 print_r($gt->interestOverTime('Donald Trump', 0 , 'today 12-m' ));
~~~~
Upon commenting out src>Google>Gtrends.php it works as expected.
~~~~
#338      // $timeInfo = explode('-', $time);
             // $timeInfo[0] = strtolower($timeInfo[0]);
             // $timeUnit = array_pop($timeInfo);
             // $timeInfo[] = strtoupper($timeUnit);
             // $time = implode('-', $timeInfo);
~~~~

PHP 7.2.10

**Comment by x-fran** [comment] 2019-01-14 08:35
Sorry but I can't reproduce the error.
I have results running:
`print_r($gt->interestOverTime('Donald Trump', 0 , 'today 12-m'));`

**Comment by rehmatworks** [comment] 2019-06-15 11:21
`$gt->interestOverTime('Donald Trump', 0 , 'today 12-m');` returns false...

**Comment by NicoEngler** [comment] 2019-12-15 18:40
returns false for me as

**Comment by x-fran** [comment] 2019-12-15 22:07
Looks like Google changed something here. I will try to fix it ASAP if nobody else is doing it meanwhile.

**Comment by x-fran** [comment] 2020-02-07 17:22
Hi guys, 

This issue hopefully is fixed in the latest [commit](https://github.com/x-fran/g-trends/commit/269ffe2611423492e6818d628b2c4a44c06352dc).
Please let me know if any issues.

Thank you.

**Closed by x-fran** 2020-02-07 17:22 UTC
